config/routes.rb
Bloccit::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' } 
  
  resources :users, only: [:show, :index] # create a route for user#show
  resources :posts, only: [:index]
  resources :topics do 
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end


  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :posts, dependent: :destroy
  scope :visible_to, lambda { |user| user ? scoped : where(public: true)}
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])  
    authorize! :read, @topic, message: "You need to be signed-in to do that." 
    @post = Post.find(params[:id]) 
    @comments = @post.comments # need to pass @comments to we can pass the collection to the comment partial
    @comment = Comment.new # need to pass @comment - create a new Comment object to pass to the form patial
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :new, Post, {message: "You need to be a member to create a new post."}
  end

  # Adding a create method to the posts_controller.rb
  # This is the action method called when a user hits Save/Submit btn
  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic

    authorize! :create, @post, message: "You need to be signed up to do that."
    if @post.save
      flash[:notice] = "Post was saved."
      # redirect_to [@topic, @post]
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."

    if @post.update_attributes(params[:post])

      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post.  Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title

    authorize! :destroy, @post, message: "You need to own the post to delete it!"
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic 
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end
end

app/controllers/topics/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
  end

  def show
    @topic = Topic.find(params[:id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @posts = @topic.posts.paginate(page: params[:page], per_page: 5)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: "You need to be an admin for that."
  end

  def create
    @topic = Topic.new(params[:topic])
    authorize! :create, @topic, message: "You need to be an admin to do that."
    if @topic.save
      flash[:notice] = "Topic saved"
      redirect_to @topic
    else
      flash[:error] = "The topic entered was not saved. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own the topic to edit it."
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own the topic to update it."
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic updated"
      redirect_to @topic
    else
      flash[:error] = "The topic you updated was not saved. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    authorize! :destroy, @topic, message: "You need to own the topic to delete it."
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was a problem deleting the topic."
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
  end

  def show
    @topic = Topic.find(params[:id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: "You need to be an admin for that."
  end

  def create
    @topic = Topic.new(params[:topic])
    authorize! :create, @topic, message: "You need to be an admin to do that."
    if @topic.save
      flash[:notice] = "Topic saved"
      redirect_to @topic
    else
      flash[:error] = "The topic entered was not saved. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own the topic to edit it."
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own the topic to update it."
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic updated"
      redirect_to @topic
    else
      flash[:error] = "The topic you updated was not saved. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    authorize! :destroy, @topic, message: "You need to own the topic to delete it."
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was a problem deleting the topic."
      render :show
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.haml
%h1 Edit Topic
.row
  .span6
    %p Guidelines for new topic:
    %ul
      %li Make sure content is appropriate.
      %li Blah blah blah
      %li Blah blah blah
      %li Blah blah blah
  .span6
    = form_for @topic, html: { class: 'form-horizontal' } do |f|
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          = f.text_field :name
      .control-group
        = f.label :description, class: 'control-label'
        .controls
          = f.text_area :description, rows: 8
      .control-group
        .controls
          = f.label :public, class: 'checkbox' do
            = f.check_box :public
            Public topic
      .control-group
        .controls
          = f.submit "Save", class: 'btn'

app/views/topics/index.html.haml
%h1 Topics
.row
  .span8
    - @topics.each do |topic|
      .media
        .media-body
          %h4.media-heading 
            = link_to topic.name, topic
          %small 
            = topic.description
    = will_paginate @topics
  .span4
    - if can? :create, Topic
      = link_to "New Topic", new_topic_path, class: 'btn btn-large btn-blo'

app/views/topics/new.html.haml
%h1 New Topic
.row
  .span6
    %p Guidelines for new posts
    %ul 
      %li Make sure content is appropriate.
      %li Blah blah blah
      %li Blah blah blah
      %li Blah blah blah
  .span6
    = form_for @topic, html: {class: 'form-horizontal'} do |f|
      .control-group
        = f.label :name, class: 'class-label'
        .controls
          = f.text_field :name
      .control-group
        =f.label :description, class: 'control-label'
        .controls
          =f.text_area :description, rows: 8
      .control-group
        .controls
          =f.submit "Save", class: 'btn'

app/views/topics/show.html.haml
%h1= @topic.name
- if can? :update, @topic
  =link_to "Edit topic", edit_topic_path, class: 'btn btn-primary btn-mini'
.row
  .span8
    %p.lead= @topic.description
    = render @posts
    = will_paginate @posts
  .span4
    - if can? :create, Post
      = link_to "New Post", new_topic_post_path(@topic), class: 'btn btn btn-large btn-block'
    - if can? :destroy, @topic
      = link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this topic?'





 