config/routes.rb
Bloccit::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' } 
  
  resources :users, only: [:show, :index] # create a route for user#show
  resources :posts, only: [:index]
  resources :topics do 
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end


  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/views/layouts/application.html.haml
!!! 5
%html 
  %head 
    %title Bloccit
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
%body 
  .container
    %ul{:class => 'nav nav-tabs'}
      %li= link_to 'Bloccit', root_path
      %li= link_to 'About', about_path
      %li= link_to 'Topics', topics_path
      %li= link_to 'Popular', posts_path
      %li= link_to 'Users', users_path
      .pull-right.user-info
        - if current_user
          = image_tag(current_user.avatar.tiny.url) if current_user.avatar?
          Hello
          = link_to (current_user.name || current_user.email), current_user 
          !
          = link_to edit_user_registration_path, class: 'btn btn-mini' do
            %i.icon-user
          = link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do
            %i.icon-share-alt
        - else
          = link_to "Sign In", new_user_session_path or link_to "Sign Up", new_user_registration_path
    - if flash[:notice]
      .alert.alert-success
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        = flash[:notice]
    - elsif flash[:error]
      .alert.alert-error
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        = flash[:error]
    - elsif flash[:alert]
      .alert
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        = flash[:alert]
    = yield
    = javascript_include_tag "application"